// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Booking", b =>
                {
                    b.Property<int>("Booking_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Booking_Id"));

                    b.Property<DateTime>("Booking_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Hall_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Hall_Id1")
                        .HasColumnType("int");

                    b.Property<int?>("Session_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Session_Id1")
                        .HasColumnType("int");

                    b.Property<int>("Ticket_amount")
                        .HasColumnType("int");

                    b.Property<int?>("User_Id")
                        .HasColumnType("int");

                    b.Property<int?>("UsersUser_Id")
                        .HasColumnType("int");

                    b.HasKey("Booking_Id");

                    b.HasIndex("Hall_Id1");

                    b.HasIndex("Session_Id1");

                    b.HasIndex("UsersUser_Id");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("api.Models.Films", b =>
                {
                    b.Property<int>("Id_films")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_films"));

                    b.Property<int>("Age_rating")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Release_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_films");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("api.Models.Hall", b =>
                {
                    b.Property<int>("Hall_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Hall_Id"));

                    b.Property<int>("Amount_seats_in_a_row")
                        .HasColumnType("int");

                    b.Property<int>("Row_amount")
                        .HasColumnType("int");

                    b.HasKey("Hall_Id");

                    b.ToTable("Hall");
                });

            modelBuilder.Entity("api.Models.Session", b =>
                {
                    b.Property<int>("Session_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Session_Id"));

                    b.Property<int>("Amount_of_empty_seats")
                        .HasColumnType("int");

                    b.Property<int?>("FilmsId_films")
                        .HasColumnType("int");

                    b.Property<int>("Hall")
                        .HasColumnType("int");

                    b.Property<int?>("Id_film")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Session_date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Session_time")
                        .HasColumnType("time");

                    b.HasKey("Session_Id");

                    b.HasIndex("FilmsId_films");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("api.Models.Users", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Regestration_date")
                        .HasColumnType("datetime2");

                    b.HasKey("User_Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("api.Models.Booking", b =>
                {
                    b.HasOne("api.Models.Hall", "Hall")
                        .WithMany("Bookings")
                        .HasForeignKey("Hall_Id1");

                    b.HasOne("api.Models.Session", "Session")
                        .WithMany("Bookings")
                        .HasForeignKey("Session_Id1");

                    b.HasOne("api.Models.Users", "Users")
                        .WithMany("Bookings")
                        .HasForeignKey("UsersUser_Id");

                    b.Navigation("Hall");

                    b.Navigation("Session");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("api.Models.Session", b =>
                {
                    b.HasOne("api.Models.Films", "Films")
                        .WithMany("Sessions")
                        .HasForeignKey("FilmsId_films");

                    b.Navigation("Films");
                });

            modelBuilder.Entity("api.Models.Films", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("api.Models.Hall", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("api.Models.Session", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("api.Models.Users", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
